spring.datasource.url=jdbc:postgresql://localhost:5432/concertly_mobile
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8082

jwt.secret=concertly-super-secret-key-change-in-production-32chars
jwt.expiration.ms=3600000
jwt.refresh.expiration.days=30

spotify.client.id=29b4fc51e0014d558bf59dedf028160d
spotify.client.secret=ba38c993f72443608efd6bfe9eb3d509
spotify.redirect.uri=http://localhost:8082/api/spotify/callback

ticketmaster.api.key=BTkNLCBxzGAGWm4sLPyGQN5MYiffGq4U